name: Notify Snapshot

on:
  workflow_dispatch:

  release:
    types: [ published ]

jobs:
  build:
    uses: Crazy-Crew/.github/.github/workflows/notify.yml@main

    with:
      webhook: ${{ secrets.CC_WEBHOOK }}

    secrets: inherit