# List of all the enchantments: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
# List of all the sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
Settings:
  Prefix: '&8[&bCrazyCrates&8]: '
  Toggle-Metrics: true #Turn on and off if your server stats are sent to https://bstats.org/ - Requires a restart!
  # Whether to enable or disable the crate menu. True if you want it enabled otherwise False
  Enable-Crate-Menu: true
  # Whether to actions to file & console.
  # Includes command failures, keys taken, given, received and so on.
  # Defaults to false.
  Crate-Actions:
    Log-File: false # Make sure to delete your log file every now & then.
    Log-Console: false
  InventoryName: '&b&lCrazy &4&lCrates'
  InventorySize: 45
  KnockBack: true
  Physical-Accepts-Virtual-Keys: true #If physical crates can accept virtual keys.
  Physical-Accepts-Physical-Keys: true # If physical crates can accept physical keys.
  Virtual-Accepts-Physical-Keys: true #If virtual crates can accept physical keys.
  Give-Virtual-Keys-When-Inventory-Full-Message: false # If the player should be notified that it was a virtual key.
  Give-Virtual-Keys-When-Inventory-Full: false #If the player's inventory is full when given a physical key it will instead give them virtual keys. If false it will drop the keys on the ground.
  Need-Key-Sound: 'ENTITY_VILLAGER_NO' #This sound plays when a player tries to open a crate with no key.
  QuadCrate:
    Timer: 300
  DisabledWorlds:
    - 'world_nether'
  Preview:
    Buttons:
      Menu:
        Item: 'COMPASS'
        Name: '&7&l>> &c&lMenu &7&l<<'
        Lore:
          - '&7Return to the menu.'
      Next:
        Item: 'FEATHER'
        Name: '&6&lNext >>'
        Lore:
          - '&7&lPage: &b%page%'
      Back:
        Item: 'FEATHER'
        Name: '&6&l<< Back'
        Lore:
          - '&7&lPage: &b%page%'
  Filler: #This allows you to quickly fill the GUI with one item.
    Toggle: false #If it fills the GUI with an item.
    Item: 'BLACK_STAINED_GLASS_PANE' #The item you wish to use.
    Name: ' ' #The name of the item.
    Lore: [] #The lore of the item.
  GUI-Customizer: #Place extra items in the GUI. If you wish to not use this, remove all items and set it to GUI-Customizer: {}
    - 'Slot:1, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:2, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:3, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:4, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:5, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:6, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:7, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:8, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:9, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:10, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:18, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:19, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:27, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:28, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:36, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:37, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:45, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:11, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:12, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:13, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:14, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:15, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:16, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:17, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:20, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:22, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:24, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:26, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:29, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:30, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:31, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:32, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:33, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:34, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:35, Item:WHITE_STAINED_GLASS_PANE, Name: '
    - 'Slot:38, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:39, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:40, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:41, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:42, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:43, Item:BLACK_STAINED_GLASS_PANE, Name: '
    - 'Slot:44, Item:BLACK_STAINED_GLASS_PANE, Name: '